title: Aikawa's Page
description: テスト
show_downloads: false
google_analytics:
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
